package com.doctorzee.fortuneblocks.utils.items;

import java.util.Map;

import com.google.common.collect.ImmutableMap;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BookMeta;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.material.MaterialData;

/**
 * A class to easily look up the actual display name of items in Minecraft. This class
 * was originally made a long time ago using only number id and data values, but it has
 * been updated to work properly with Bukkit's Material enum.
 *
 * @author Michael Ziluck
 * @version 1.13.2
 */
public class ItemNames
{

    private static final Map<Material, String> ITEM_NAMES;

    static
    {
        ITEM_NAMES = ImmutableMap.<Material, String>builder()
                             .put(Material.ACACIA_BOAT, "Acacia Boat")
                             .put(Material.ACACIA_BUTTON, "Acacia Button")
                             .put(Material.ACACIA_DOOR, "Acacia Door")
                             .put(Material.ACACIA_FENCE, "Acacia Fence")
                             .put(Material.ACACIA_FENCE_GATE, "Acacia Fence Gate")
                             .put(Material.ACACIA_LEAVES, "Acacia Leaves")
                             .put(Material.ACACIA_LOG, "Acacia Log")
                             .put(Material.ACACIA_PLANKS, "Acacia Planks")
                             .put(Material.ACACIA_PRESSURE_PLATE, "Acacia Pressure Plate")
                             .put(Material.ACACIA_SAPLING, "Acacia Sapling")
                             .put(Material.ACACIA_SLAB, "Acacia Slab")
                             .put(Material.ACACIA_STAIRS, "Acacia Stairs")
                             .put(Material.ACACIA_TRAPDOOR, "Acacia Trapdoor")
                             .put(Material.ACACIA_WOOD, "Acacia Wood")
                             .put(Material.ACTIVATOR_RAIL, "Activator Rail")
                             .put(Material.AIR, "Air")
                             .put(Material.ALLIUM, "Allium")
                             .put(Material.ANDESITE, "Andesite")
                             .put(Material.ANVIL, "Anvil")
                             .put(Material.APPLE, "Apple")
                             .put(Material.ARMOR_STAND, "Armor Stand")
                             .put(Material.ARROW, "Arrow")
                             .put(Material.ATTACHED_MELON_STEM, "Attached Melon Stem")
                             .put(Material.ATTACHED_PUMPKIN_STEM, "Attached Pumpkin Stem")
                             .put(Material.AZURE_BLUET, "Azure Bluet")
                             .put(Material.BAKED_POTATO, "Baked Potato")
                             .put(Material.BARRIER, "Barrier")
                             .put(Material.BAT_SPAWN_EGG, "Bat Spawn Egg")
                             .put(Material.BEACON, "Beacon")
                             .put(Material.BEDROCK, "Bedrock")
                             .put(Material.BEEF, "Raw Beef")
                             .put(Material.BEETROOT, "Beetroot")
                             .put(Material.BEETROOTS, "Beetroots")
                             .put(Material.BEETROOT_SEEDS, "Beetroot Seeds")
                             .put(Material.BEETROOT_SOUP, "Beetroot Soup")
                             .put(Material.BIRCH_BOAT, "Birch Boat")
                             .put(Material.BIRCH_BUTTON, "Birch Button")
                             .put(Material.BIRCH_DOOR, "Birch Door")
                             .put(Material.BIRCH_FENCE, "Birch Fence")
                             .put(Material.BIRCH_FENCE_GATE, "Birch Fence Gate")
                             .put(Material.BIRCH_LEAVES, "Birch Leaves")
                             .put(Material.BIRCH_LOG, "Birch Log")
                             .put(Material.BIRCH_PLANKS, "Birch Planks")
                             .put(Material.BIRCH_PRESSURE_PLATE, "Birch Pressure Plate")
                             .put(Material.BIRCH_SAPLING, "Birch Sapling")
                             .put(Material.BIRCH_SLAB, "Birch Slab")
                             .put(Material.BIRCH_STAIRS, "Birch Stairs")
                             .put(Material.BIRCH_TRAPDOOR, "Birch Trapdoor")
                             .put(Material.BIRCH_WOOD, "Birch Wood")
                             .put(Material.BLACK_BANNER, "Black Banner")
                             .put(Material.BLACK_BED, "Black Bed")
                             .put(Material.BLACK_CARPET, "Black Carpet")
                             .put(Material.BLACK_CONCRETE, "Black Concrete")
                             .put(Material.BLACK_CONCRETE_POWDER, "Black Concrete Powder")
                             .put(Material.BLACK_GLAZED_TERRACOTTA, "Black Glazed Terracotta")
                             .put(Material.BLACK_SHULKER_BOX, "Black Shulker Box")
                             .put(Material.BLACK_STAINED_GLASS, "Black Stained Glass")
                             .put(Material.BLACK_STAINED_GLASS_PANE, "Black Stained Glass Pane")
                             .put(Material.BLACK_TERRACOTTA, "Black Terracotta")
                             .put(Material.BLACK_WALL_BANNER, "Black Banner")
                             .put(Material.BLACK_WOOL, "Black Wool")
                             .put(Material.BLAZE_POWDER, "Blaze Powder")
                             .put(Material.BLAZE_ROD, "Blaze Rod")
                             .put(Material.BLAZE_SPAWN_EGG, "Blaze Spawn Egg")
                             .put(Material.BLUE_BANNER, "Blue Banner")
                             .put(Material.BLUE_BED, "Blue Bed")
                             .put(Material.BLUE_CARPET, "Blue Carpet")
                             .put(Material.BLUE_CONCRETE, "Blue Concrete")
                             .put(Material.BLUE_CONCRETE_POWDER, "Blue Concrete Powder")
                             .put(Material.BLUE_GLAZED_TERRACOTTA, "Blue Glazed Terracotta")
                             .put(Material.BLUE_ICE, "Blue Ice")
                             .put(Material.BLUE_ORCHID, "Blue Orchid")
                             .put(Material.BLUE_SHULKER_BOX, "Blue Shulker Box")
                             .put(Material.BLUE_STAINED_GLASS, "Blue Stained Glass")
                             .put(Material.BLUE_STAINED_GLASS_PANE, "Blue Stained Glass Pane")
                             .put(Material.BLUE_TERRACOTTA, "Blue Terracotta")
                             .put(Material.BLUE_WALL_BANNER, "Blue Banner")
                             .put(Material.BLUE_WOOL, "Blue Wool")
                             .put(Material.BONE, "Bone")
                             .put(Material.BONE_BLOCK, "Bone Block")
                             .put(Material.BONE_MEAL, "Bone Meal")
                             .put(Material.BOOK, "Book")
                             .put(Material.BOOKSHELF, "Bookshelf")
                             .put(Material.BOW, "Bow")
                             .put(Material.BOWL, "Bowl")
                             .put(Material.BRAIN_CORAL, "Brain Coral")
                             .put(Material.BRAIN_CORAL_BLOCK, "Brain Coral Block")
                             .put(Material.BRAIN_CORAL_FAN, "Brain Coral Fan")
                             .put(Material.BRAIN_CORAL_WALL_FAN, "Brain Coral Wall Fan")
                             .put(Material.BREAD, "Bread")
                             .put(Material.BREWING_STAND, "Brewing Stand")
                             .put(Material.BRICK, "Brick")
                             .put(Material.BRICKS, "Bricks")
                             .put(Material.BRICK_SLAB, "Brick Slab")
                             .put(Material.BRICK_STAIRS, "Brick Stairs")
                             .put(Material.BROWN_BANNER, "Brown Banner")
                             .put(Material.BROWN_BED, "Brown Bed")
                             .put(Material.BROWN_CARPET, "Brown Carpet")
                             .put(Material.BROWN_CONCRETE, "Brown Concrete")
                             .put(Material.BROWN_CONCRETE_POWDER, "Brown Concrete Powder")
                             .put(Material.BROWN_GLAZED_TERRACOTTA, "Brown Glazed Terracotta")
                             .put(Material.BROWN_MUSHROOM, "Brown Mushroom")
                             .put(Material.BROWN_MUSHROOM_BLOCK, "Brown Mushroom Block")
                             .put(Material.BROWN_SHULKER_BOX, "Brown Shulker Box")
                             .put(Material.BROWN_STAINED_GLASS, "Brown Stained Glass")
                             .put(Material.BROWN_STAINED_GLASS_PANE, "Brown Stained Glass Pane")
                             .put(Material.BROWN_TERRACOTTA, "Brown Terracotta")
                             .put(Material.BROWN_WALL_BANNER, "Brown Banner")
                             .put(Material.BROWN_WOOL, "Brown Wool")
                             .put(Material.BUBBLE_COLUMN, "Bubble Column")
                             .put(Material.BUBBLE_CORAL, "Bubble Coral")
                             .put(Material.BUBBLE_CORAL_BLOCK, "Bubble Coral Block")
                             .put(Material.BUBBLE_CORAL_FAN, "Bubble Coral Fan")
                             .put(Material.BUBBLE_CORAL_WALL_FAN, "Bubble Coral Wall Fan")
                             .put(Material.BUCKET, "Bucket")
                             .put(Material.CACTUS, "Cactus")
                             .put(Material.CACTUS_GREEN, "Cactus Green")
                             .put(Material.CAKE, "Cake")
                             .put(Material.CARROT, "Carrot")
                             .put(Material.CARROTS, "Carrots")
                             .put(Material.CARROT_ON_A_STICK, "Carrot on a Stick")
                             .put(Material.CARVED_PUMPKIN, "Carved Pumpkin")
                             .put(Material.CAULDRON, "Cauldron")
                             .put(Material.CAVE_AIR, "Cave Air")
                             .put(Material.CAVE_SPIDER_SPAWN_EGG, "Cave Spider Spawn Egg")
                             .put(Material.CHAINMAIL_BOOTS, "Chainmail Boots")
                             .put(Material.CHAINMAIL_CHESTPLATE, "Chainmail Chestplate")
                             .put(Material.CHAINMAIL_HELMET, "Chainmail Helmet")
                             .put(Material.CHAINMAIL_LEGGINGS, "Chainmail Leggings")
                             .put(Material.CHAIN_COMMAND_BLOCK, "Chain Command Block")
                             .put(Material.CHARCOAL, "Charcoal")
                             .put(Material.CHEST, "Chest")
                             .put(Material.CHEST_MINECART, "Minecart with Chest")
                             .put(Material.CHICKEN, "Raw Chicken")
                             .put(Material.CHICKEN_SPAWN_EGG, "Chicken Spawn Egg")
                             .put(Material.CHIPPED_ANVIL, "Chipped Anvil")
                             .put(Material.CHISELED_QUARTZ_BLOCK, "Chiseled Quartz Block")
                             .put(Material.CHISELED_RED_SANDSTONE, "Chiseled Red Sandstone")
                             .put(Material.CHISELED_SANDSTONE, "Chiseled Sandstone")
                             .put(Material.CHISELED_STONE_BRICKS, "Chiseled Stone Bricks")
                             .put(Material.CHORUS_FLOWER, "Chorus Flower")
                             .put(Material.CHORUS_FRUIT, "Chorus Fruit")
                             .put(Material.CHORUS_PLANT, "Chorus Plant")
                             .put(Material.CLAY, "Clay")
                             .put(Material.CLAY_BALL, "Clay")
                             .put(Material.CLOCK, "Clock")
                             .put(Material.COAL, "Coal")
                             .put(Material.COAL_BLOCK, "Block of Coal")
                             .put(Material.COAL_ORE, "Coal Ore")
                             .put(Material.COARSE_DIRT, "Coarse Dirt")
                             .put(Material.COBBLESTONE, "Cobblestone")
                             .put(Material.COBBLESTONE_SLAB, "Cobblestone Slab")
                             .put(Material.COBBLESTONE_STAIRS, "Cobblestone Stairs")
                             .put(Material.COBBLESTONE_WALL, "Cobblestone Wall")
                             .put(Material.COBWEB, "Cobweb")
                             .put(Material.COCOA, "Cocoa")
                             .put(Material.COCOA_BEANS, "Cocoa Beans")
                             .put(Material.COD, "Raw Cod")
                             .put(Material.COD_BUCKET, "Bucket of Cod")
                             .put(Material.COD_SPAWN_EGG, "Cod Spawn Egg")
                             .put(Material.COMMAND_BLOCK, "Command Block")
                             .put(Material.COMMAND_BLOCK_MINECART, "Minecart with Command Block")
                             .put(Material.COMPARATOR, "Redstone Comparator")
                             .put(Material.COMPASS, "Compass")
                             .put(Material.CONDUIT, "Conduit")
                             .put(Material.COOKED_BEEF, "Steak")
                             .put(Material.COOKED_CHICKEN, "Cooked Chicken")
                             .put(Material.COOKED_COD, "Cooked Cod")
                             .put(Material.COOKED_MUTTON, "Cooked Mutton")
                             .put(Material.COOKED_PORKCHOP, "Cooked Porkchop")
                             .put(Material.COOKED_RABBIT, "Cooked Rabbit")
                             .put(Material.COOKED_SALMON, "Cooked Salmon")
                             .put(Material.COOKIE, "Cookie")
                             .put(Material.COW_SPAWN_EGG, "Cow Spawn Egg")
                             .put(Material.CRACKED_STONE_BRICKS, "Cracked Stone Bricks")
                             .put(Material.CRAFTING_TABLE, "Crafting Table")
                             .put(Material.CREEPER_HEAD, "Creeper Head")
                             .put(Material.CREEPER_SPAWN_EGG, "Creeper Spawn Egg")
                             .put(Material.CREEPER_WALL_HEAD, "Creeper Wall Head")
                             .put(Material.CUT_RED_SANDSTONE, "Cut Red Sandstone")
                             .put(Material.CUT_SANDSTONE, "Cut Sandstone")
                             .put(Material.CYAN_BANNER, "Cyan Banner")
                             .put(Material.CYAN_BED, "Cyan Bed")
                             .put(Material.CYAN_CARPET, "Cyan Carpet")
                             .put(Material.CYAN_CONCRETE, "Cyan Concrete")
                             .put(Material.CYAN_CONCRETE_POWDER, "Cyan Concrete Powder")
                             .put(Material.CYAN_DYE, "Cyan Dye")
                             .put(Material.CYAN_GLAZED_TERRACOTTA, "Cyan Glazed Terracotta")
                             .put(Material.CYAN_SHULKER_BOX, "Cyan Shulker Box")
                             .put(Material.CYAN_STAINED_GLASS, "Cyan Stained Glass")
                             .put(Material.CYAN_STAINED_GLASS_PANE, "Cyan Stained Glass Pane")
                             .put(Material.CYAN_TERRACOTTA, "Cyan Terracotta")
                             .put(Material.CYAN_WALL_BANNER, "Cyan Banner")
                             .put(Material.CYAN_WOOL, "Cyan Wool")
                             .put(Material.DAMAGED_ANVIL, "Damaged Anvil")
                             .put(Material.DANDELION, "Dandelion")
                             .put(Material.DANDELION_YELLOW, "Dandelion Yellow")
                             .put(Material.DARK_OAK_BOAT, "Dark Oak Boat")
                             .put(Material.DARK_OAK_BUTTON, "Dark Oak Button")
                             .put(Material.DARK_OAK_DOOR, "Dark Oak Door")
                             .put(Material.DARK_OAK_FENCE, "Dark Oak Fence")
                             .put(Material.DARK_OAK_FENCE_GATE, "Dark Oak Fence Gate")
                             .put(Material.DARK_OAK_LEAVES, "Dark Oak Leaves")
                             .put(Material.DARK_OAK_LOG, "Dark Oak Log")
                             .put(Material.DARK_OAK_PLANKS, "Dark Oak Planks")
                             .put(Material.DARK_OAK_PRESSURE_PLATE, "Dark Oak Pressure Plate")
                             .put(Material.DARK_OAK_SAPLING, "Dark Oak Sapling")
                             .put(Material.DARK_OAK_SLAB, "Dark Oak Slab")
                             .put(Material.DARK_OAK_STAIRS, "Dark Oak Stairs")
                             .put(Material.DARK_OAK_TRAPDOOR, "Dark Oak Trapdoor")
                             .put(Material.DARK_OAK_WOOD, "Dark Oak Wood")
                             .put(Material.DARK_PRISMARINE, "Dark Prismarine")
                             .put(Material.DARK_PRISMARINE_SLAB, "Dark Prismarine Slab")
                             .put(Material.DARK_PRISMARINE_STAIRS, "Dark Prismarine Stairs")
                             .put(Material.DAYLIGHT_DETECTOR, "Daylight Detector")
                             .put(Material.DEAD_BRAIN_CORAL, "Dead Brain Coral")
                             .put(Material.DEAD_BRAIN_CORAL_BLOCK, "Dead Brain Coral Block")
                             .put(Material.DEAD_BRAIN_CORAL_FAN, "Dead Brain Coral Fan")
                             .put(Material.DEAD_BRAIN_CORAL_WALL_FAN, "Dead Brain Coral Wall Fan")
                             .put(Material.DEAD_BUBBLE_CORAL, "Dead Bubble Coral")
                             .put(Material.DEAD_BUBBLE_CORAL_BLOCK, "Dead Bubble Coral Block")
                             .put(Material.DEAD_BUBBLE_CORAL_FAN, "Dead Bubble Coral Fan")
                             .put(Material.DEAD_BUBBLE_CORAL_WALL_FAN, "Dead Bubble Coral Wall Fan")
                             .put(Material.DEAD_BUSH, "Dead Bush")
                             .put(Material.DEAD_FIRE_CORAL, "Dead Fire Coral")
                             .put(Material.DEAD_FIRE_CORAL_BLOCK, "Dead Fire Coral Block")
                             .put(Material.DEAD_FIRE_CORAL_FAN, "Dead Fire Coral Fan")
                             .put(Material.DEAD_FIRE_CORAL_WALL_FAN, "Dead Fire Coral Wall Fan")
                             .put(Material.DEAD_HORN_CORAL, "Dead Horn Coral")
                             .put(Material.DEAD_HORN_CORAL_BLOCK, "Dead Horn Coral Block")
                             .put(Material.DEAD_HORN_CORAL_FAN, "Dead Horn Coral Fan")
                             .put(Material.DEAD_HORN_CORAL_WALL_FAN, "Dead Horn Coral Wall Fan")
                             .put(Material.DEAD_TUBE_CORAL, "Dead Tube Coral")
                             .put(Material.DEAD_TUBE_CORAL_BLOCK, "Dead Tube Coral Block")
                             .put(Material.DEAD_TUBE_CORAL_FAN, "Dead Tube Coral Fan")
                             .put(Material.DEAD_TUBE_CORAL_WALL_FAN, "Dead Tube Coral Wall Fan")
                             .put(Material.DEBUG_STICK, "Debug Stick")
                             .put(Material.DETECTOR_RAIL, "Detector Rail")
                             .put(Material.DIAMOND, "Diamond")
                             .put(Material.DIAMOND_AXE, "Diamond Axe")
                             .put(Material.DIAMOND_BLOCK, "Block of Diamond")
                             .put(Material.DIAMOND_BOOTS, "Diamond Boots")
                             .put(Material.DIAMOND_CHESTPLATE, "Diamond Chestplate")
                             .put(Material.DIAMOND_HELMET, "Diamond Helmet")
                             .put(Material.DIAMOND_HOE, "Diamond Hoe")
                             .put(Material.DIAMOND_HORSE_ARMOR, "Diamond Horse Armor")
                             .put(Material.DIAMOND_LEGGINGS, "Diamond Leggings")
                             .put(Material.DIAMOND_ORE, "Diamond Ore")
                             .put(Material.DIAMOND_PICKAXE, "Diamond Pickaxe")
                             .put(Material.DIAMOND_SHOVEL, "Diamond Shovel")
                             .put(Material.DIAMOND_SWORD, "Diamond Sword")
                             .put(Material.DIORITE, "Diorite")
                             .put(Material.DIRT, "Dirt")
                             .put(Material.DISPENSER, "Dispenser")
                             .put(Material.DOLPHIN_SPAWN_EGG, "Dolphin Spawn Egg")
                             .put(Material.DONKEY_SPAWN_EGG, "Donkey Spawn Egg")
                             .put(Material.DRAGON_BREATH, "Dragon's Breath")
                             .put(Material.DRAGON_EGG, "Dragon Egg")
                             .put(Material.DRAGON_HEAD, "Dragon Head")
                             .put(Material.DRAGON_WALL_HEAD, "Dragon Wall Head")
                             .put(Material.DRIED_KELP, "Dried Kelp")
                             .put(Material.DRIED_KELP_BLOCK, "Dried Kelp Block")
                             .put(Material.DROPPER, "Dropper")
                             .put(Material.DROWNED_SPAWN_EGG, "Drowned Spawn Egg")
                             .put(Material.EGG, "Egg")
                             .put(Material.ELDER_GUARDIAN_SPAWN_EGG, "Elder Guardian Spawn Egg")
                             .put(Material.ELYTRA, "Elytra")
                             .put(Material.EMERALD, "Emerald")
                             .put(Material.EMERALD_BLOCK, "Block of Emerald")
                             .put(Material.EMERALD_ORE, "Emerald Ore")
                             .put(Material.ENCHANTED_BOOK, "Enchanted Book")
                             .put(Material.ENCHANTED_GOLDEN_APPLE, "Enchanted Golden Apple")
                             .put(Material.ENCHANTING_TABLE, "Enchanting Table")
                             .put(Material.ENDERMAN_SPAWN_EGG, "Enderman Spawn Egg")
                             .put(Material.ENDERMITE_SPAWN_EGG, "Endermite Spawn Egg")
                             .put(Material.ENDER_CHEST, "Ender Chest")
                             .put(Material.ENDER_EYE, "Eye of Ender")
                             .put(Material.ENDER_PEARL, "Ender Pearl")
                             .put(Material.END_CRYSTAL, "End Crystal")
                             .put(Material.END_GATEWAY, "End Gateway")
                             .put(Material.END_PORTAL, "End Portal")
                             .put(Material.END_PORTAL_FRAME, "End Portal Frame")
                             .put(Material.END_ROD, "End Rod")
                             .put(Material.END_STONE, "End Stone")
                             .put(Material.END_STONE_BRICKS, "End Stone Bricks")
                             .put(Material.EVOKER_SPAWN_EGG, "Evoker Spawn Egg")
                             .put(Material.EXPERIENCE_BOTTLE, "Bottle o' Enchanting")
                             .put(Material.FARMLAND, "Farmland")
                             .put(Material.FEATHER, "Feather")
                             .put(Material.FERMENTED_SPIDER_EYE, "Fermented Spider Eye")
                             .put(Material.FERN, "Fern")
                             .put(Material.FILLED_MAP, "Map")
                             .put(Material.FIRE, "Fire")
                             .put(Material.FIREWORK_ROCKET, "Firework Rocket")
                             .put(Material.FIREWORK_STAR, "Firework Star")
                             .put(Material.FIRE_CHARGE, "Fire Charge")
                             .put(Material.FIRE_CORAL, "Fire Coral")
                             .put(Material.FIRE_CORAL_BLOCK, "Fire Coral Block")
                             .put(Material.FIRE_CORAL_FAN, "Fire Coral Fan")
                             .put(Material.FIRE_CORAL_WALL_FAN, "Fire Coral Wall Fan")
                             .put(Material.FISHING_ROD, "Fishing Rod")
                             .put(Material.FLINT, "Flint")
                             .put(Material.FLINT_AND_STEEL, "Flint and Steel")
                             .put(Material.FLOWER_POT, "Flower Pot")
                             .put(Material.FROSTED_ICE, "Frosted Ice")
                             .put(Material.FURNACE, "Furnace")
                             .put(Material.FURNACE_MINECART, "Minecart with Furnace")
                             .put(Material.GHAST_SPAWN_EGG, "Ghast Spawn Egg")
                             .put(Material.GHAST_TEAR, "Ghast Tear")
                             .put(Material.GLASS, "Glass")
                             .put(Material.GLASS_BOTTLE, "Glass Bottle")
                             .put(Material.GLASS_PANE, "Glass Pane")
                             .put(Material.GLISTERING_MELON_SLICE, "Glistering Melon Slice")
                             .put(Material.GLOWSTONE, "Glowstone")
                             .put(Material.GLOWSTONE_DUST, "Glowstone Dust")
                             .put(Material.GOLDEN_APPLE, "Golden Apple")
                             .put(Material.GOLDEN_AXE, "Golden Axe")
                             .put(Material.GOLDEN_BOOTS, "Golden Boots")
                             .put(Material.GOLDEN_CARROT, "Golden Carrot")
                             .put(Material.GOLDEN_CHESTPLATE, "Golden Chestplate")
                             .put(Material.GOLDEN_HELMET, "Golden Helmet")
                             .put(Material.GOLDEN_HOE, "Golden Hoe")
                             .put(Material.GOLDEN_HORSE_ARMOR, "Golden Horse Armor")
                             .put(Material.GOLDEN_LEGGINGS, "Golden Leggings")
                             .put(Material.GOLDEN_PICKAXE, "Golden Pickaxe")
                             .put(Material.GOLDEN_SHOVEL, "Golden Shovel")
                             .put(Material.GOLDEN_SWORD, "Golden Sword")
                             .put(Material.GOLD_BLOCK, "Block of Gold")
                             .put(Material.GOLD_INGOT, "Gold Ingot")
                             .put(Material.GOLD_NUGGET, "Gold Nugget")
                             .put(Material.GOLD_ORE, "Gold Ore")
                             .put(Material.GRANITE, "Granite")
                             .put(Material.GRASS, "Grass")
                             .put(Material.GRASS_BLOCK, "Grass Block")
                             .put(Material.GRASS_PATH, "Grass Path")
                             .put(Material.GRAVEL, "Gravel")
                             .put(Material.GRAY_BANNER, "Gray Banner")
                             .put(Material.GRAY_BED, "Gray Bed")
                             .put(Material.GRAY_CARPET, "Gray Carpet")
                             .put(Material.GRAY_CONCRETE, "Gray Concrete")
                             .put(Material.GRAY_CONCRETE_POWDER, "Gray Concrete Powder")
                             .put(Material.GRAY_DYE, "Gray Dye")
                             .put(Material.GRAY_GLAZED_TERRACOTTA, "Gray Glazed Terracotta")
                             .put(Material.GRAY_SHULKER_BOX, "Gray Shulker Box")
                             .put(Material.GRAY_STAINED_GLASS, "Gray Stained Glass")
                             .put(Material.GRAY_STAINED_GLASS_PANE, "Gray Stained Glass Pane")
                             .put(Material.GRAY_TERRACOTTA, "Gray Terracotta")
                             .put(Material.GRAY_WALL_BANNER, "Gray Banner")
                             .put(Material.GRAY_WOOL, "Gray Wool")
                             .put(Material.GREEN_BANNER, "Green Banner")
                             .put(Material.GREEN_BED, "Green Bed")
                             .put(Material.GREEN_CARPET, "Green Carpet")
                             .put(Material.GREEN_CONCRETE, "Green Concrete")
                             .put(Material.GREEN_CONCRETE_POWDER, "Green Concrete Powder")
                             .put(Material.GREEN_GLAZED_TERRACOTTA, "Green Glazed Terracotta")
                             .put(Material.GREEN_SHULKER_BOX, "Green Shulker Box")
                             .put(Material.GREEN_STAINED_GLASS, "Green Stained Glass")
                             .put(Material.GREEN_STAINED_GLASS_PANE, "Green Stained Glass Pane")
                             .put(Material.GREEN_TERRACOTTA, "Green Terracotta")
                             .put(Material.GREEN_WALL_BANNER, "Green Banner")
                             .put(Material.GREEN_WOOL, "Green Wool")
                             .put(Material.GUARDIAN_SPAWN_EGG, "Guardian Spawn Egg")
                             .put(Material.GUNPOWDER, "Gunpowder")
                             .put(Material.HAY_BLOCK, "Hay Bale")
                             .put(Material.HEART_OF_THE_SEA, "Heart of the Sea")
                             .put(Material.HEAVY_WEIGHTED_PRESSURE_PLATE, "Heavy Weighted Pressure Plate")
                             .put(Material.HOPPER, "Hopper")
                             .put(Material.HOPPER_MINECART, "Minecart with Hopper")
                             .put(Material.HORN_CORAL, "Horn Coral")
                             .put(Material.HORN_CORAL_BLOCK, "Horn Coral Block")
                             .put(Material.HORN_CORAL_FAN, "Horn Coral Fan")
                             .put(Material.HORN_CORAL_WALL_FAN, "Horn Coral Wall Fan")
                             .put(Material.HORSE_SPAWN_EGG, "Horse Spawn Egg")
                             .put(Material.HUSK_SPAWN_EGG, "Husk Spawn Egg")
                             .put(Material.ICE, "Ice")
                             .put(Material.INFESTED_CHISELED_STONE_BRICKS, "Infested Chiseled Stone Bricks")
                             .put(Material.INFESTED_COBBLESTONE, "Infested Cobblestone")
                             .put(Material.INFESTED_CRACKED_STONE_BRICKS, "Infested Cracked Stone Bricks")
                             .put(Material.INFESTED_MOSSY_STONE_BRICKS, "Infested Mossy Stone Bricks")
                             .put(Material.INFESTED_STONE, "Infested Stone")
                             .put(Material.INFESTED_STONE_BRICKS, "Infested Stone Bricks")
                             .put(Material.INK_SAC, "Ink Sac")
                             .put(Material.IRON_AXE, "Iron Axe")
                             .put(Material.IRON_BARS, "Iron Bars")
                             .put(Material.IRON_BLOCK, "Block of Iron")
                             .put(Material.IRON_BOOTS, "Iron Boots")
                             .put(Material.IRON_CHESTPLATE, "Iron Chestplate")
                             .put(Material.IRON_DOOR, "Iron Door")
                             .put(Material.IRON_HELMET, "Iron Helmet")
                             .put(Material.IRON_HOE, "Iron Hoe")
                             .put(Material.IRON_HORSE_ARMOR, "Iron Horse Armor")
                             .put(Material.IRON_INGOT, "Iron Ingot")
                             .put(Material.IRON_LEGGINGS, "Iron Leggings")
                             .put(Material.IRON_NUGGET, "Iron Nugget")
                             .put(Material.IRON_ORE, "Iron Ore")
                             .put(Material.IRON_PICKAXE, "Iron Pickaxe")
                             .put(Material.IRON_SHOVEL, "Iron Shovel")
                             .put(Material.IRON_SWORD, "Iron Sword")
                             .put(Material.IRON_TRAPDOOR, "Iron Trapdoor")
                             .put(Material.ITEM_FRAME, "Item Frame")
                             .put(Material.JACK_O_LANTERN, "Jack o'Lantern")
                             .put(Material.JUKEBOX, "Jukebox")
                             .put(Material.JUNGLE_BOAT, "Jungle Boat")
                             .put(Material.JUNGLE_BUTTON, "Jungle Button")
                             .put(Material.JUNGLE_DOOR, "Jungle Door")
                             .put(Material.JUNGLE_FENCE, "Jungle Fence")
                             .put(Material.JUNGLE_FENCE_GATE, "Jungle Fence Gate")
                             .put(Material.JUNGLE_LEAVES, "Jungle Leaves")
                             .put(Material.JUNGLE_LOG, "Jungle Log")
                             .put(Material.JUNGLE_PLANKS, "Jungle Planks")
                             .put(Material.JUNGLE_PRESSURE_PLATE, "Jungle Pressure Plate")
                             .put(Material.JUNGLE_SAPLING, "Jungle Sapling")
                             .put(Material.JUNGLE_SLAB, "Jungle Slab")
                             .put(Material.JUNGLE_STAIRS, "Jungle Stairs")
                             .put(Material.JUNGLE_TRAPDOOR, "Jungle Trapdoor")
                             .put(Material.JUNGLE_WOOD, "Jungle Wood")
                             .put(Material.KELP, "Kelp")
                             .put(Material.KELP_PLANT, "Kelp Plant")
                             .put(Material.KNOWLEDGE_BOOK, "Knowledge Book")
                             .put(Material.LADDER, "Ladder")
                             .put(Material.LAPIS_BLOCK, "Lapis Lazuli Block")
                             .put(Material.LAPIS_LAZULI, "Lapis Lazuli")
                             .put(Material.LAPIS_ORE, "Lapis Lazuli Ore")
                             .put(Material.LARGE_FERN, "Large Fern")
                             .put(Material.LAVA, "Lava")
                             .put(Material.LAVA_BUCKET, "Lava Bucket")
                             .put(Material.LEAD, "Lead")
                             .put(Material.LEATHER, "Leather")
                             .put(Material.LEATHER_BOOTS, "Leather Boots")
                             .put(Material.LEATHER_CHESTPLATE, "Leather Tunic")
                             .put(Material.LEATHER_HELMET, "Leather Cap")
                             .put(Material.LEATHER_LEGGINGS, "Leather Pants")
                             .put(Material.LEVER, "Lever")
                             .put(Material.LIGHT_BLUE_BANNER, "Light Blue Banner")
                             .put(Material.LIGHT_BLUE_BED, "Light Blue Bed")
                             .put(Material.LIGHT_BLUE_CARPET, "Light Blue Carpet")
                             .put(Material.LIGHT_BLUE_CONCRETE, "Light Blue Concrete")
                             .put(Material.LIGHT_BLUE_CONCRETE_POWDER, "Light Blue Concrete Powder")
                             .put(Material.LIGHT_BLUE_DYE, "Light Blue Dye")
                             .put(Material.LIGHT_BLUE_GLAZED_TERRACOTTA, "Light Blue Glazed Terracotta")
                             .put(Material.LIGHT_BLUE_SHULKER_BOX, "Light Blue Shulker Box")
                             .put(Material.LIGHT_BLUE_STAINED_GLASS, "Light Blue Stained Glass")
                             .put(Material.LIGHT_BLUE_STAINED_GLASS_PANE, "Light Blue Stained Glass Pane")
                             .put(Material.LIGHT_BLUE_TERRACOTTA, "Light Blue Terracotta")
                             .put(Material.LIGHT_BLUE_WALL_BANNER, "Light Blue Banner")
                             .put(Material.LIGHT_BLUE_WOOL, "Light Blue Wool")
                             .put(Material.LIGHT_GRAY_BANNER, "Light Gray Banner")
                             .put(Material.LIGHT_GRAY_BED, "Light Gray Bed")
                             .put(Material.LIGHT_GRAY_CARPET, "Light Gray Carpet")
                             .put(Material.LIGHT_GRAY_CONCRETE, "Light Gray Concrete")
                             .put(Material.LIGHT_GRAY_CONCRETE_POWDER, "Light Gray Concrete Powder")
                             .put(Material.LIGHT_GRAY_DYE, "Light Gray Dye")
                             .put(Material.LIGHT_GRAY_GLAZED_TERRACOTTA, "Light Gray Glazed Terracotta")
                             .put(Material.LIGHT_GRAY_SHULKER_BOX, "Light Gray Shulker Box")
                             .put(Material.LIGHT_GRAY_STAINED_GLASS, "Light Gray Stained Glass")
                             .put(Material.LIGHT_GRAY_STAINED_GLASS_PANE, "Light Gray Stained Glass Pane")
                             .put(Material.LIGHT_GRAY_TERRACOTTA, "Light Gray Terracotta")
                             .put(Material.LIGHT_GRAY_WALL_BANNER, "Light Gray Banner")
                             .put(Material.LIGHT_GRAY_WOOL, "Light Gray Wool")
                             .put(Material.LIGHT_WEIGHTED_PRESSURE_PLATE, "Light Weighted Pressure Plate")
                             .put(Material.LILAC, "Lilac")
                             .put(Material.LILY_PAD, "Lily Pad")
                             .put(Material.LIME_BANNER, "Lime Banner")
                             .put(Material.LIME_BED, "Lime Bed")
                             .put(Material.LIME_CARPET, "Lime Carpet")
                             .put(Material.LIME_CONCRETE, "Lime Concrete")
                             .put(Material.LIME_CONCRETE_POWDER, "Lime Concrete Powder")
                             .put(Material.LIME_DYE, "Lime Dye")
                             .put(Material.LIME_GLAZED_TERRACOTTA, "Lime Glazed Terracotta")
                             .put(Material.LIME_SHULKER_BOX, "Lime Shulker Box")
                             .put(Material.LIME_STAINED_GLASS, "Lime Stained Glass")
                             .put(Material.LIME_STAINED_GLASS_PANE, "Lime Stained Glass Pane")
                             .put(Material.LIME_TERRACOTTA, "Lime Terracotta")
                             .put(Material.LIME_WALL_BANNER, "Lime Banner")
                             .put(Material.LIME_WOOL, "Lime Wool")
                             .put(Material.LINGERING_POTION, "Lingering Potion")
                             .put(Material.LLAMA_SPAWN_EGG, "Llama Spawn Egg")
                             .put(Material.MAGENTA_BANNER, "Magenta Banner")
                             .put(Material.MAGENTA_BED, "Magenta Bed")
                             .put(Material.MAGENTA_CARPET, "Magenta Carpet")
                             .put(Material.MAGENTA_CONCRETE, "Magenta Concrete")
                             .put(Material.MAGENTA_CONCRETE_POWDER, "Magenta Concrete Powder")
                             .put(Material.MAGENTA_DYE, "Magenta Dye")
                             .put(Material.MAGENTA_GLAZED_TERRACOTTA, "Magenta Glazed Terracotta")
                             .put(Material.MAGENTA_SHULKER_BOX, "Magenta Shulker Box")
                             .put(Material.MAGENTA_STAINED_GLASS, "Magenta Stained Glass")
                             .put(Material.MAGENTA_STAINED_GLASS_PANE, "Magenta Stained Glass Pane")
                             .put(Material.MAGENTA_TERRACOTTA, "Magenta Terracotta")
                             .put(Material.MAGENTA_WALL_BANNER, "Magenta Banner")
                             .put(Material.MAGENTA_WOOL, "Magenta Wool")
                             .put(Material.MAGMA_BLOCK, "Magma Block")
                             .put(Material.MAGMA_CREAM, "Magma Cream")
                             .put(Material.MAGMA_CUBE_SPAWN_EGG, "Magma Cube Spawn Egg")
                             .put(Material.MAP, "Empty Map")
                             .put(Material.MELON, "Melon")
                             .put(Material.MELON_SEEDS, "Melon Seeds")
                             .put(Material.MELON_SLICE, "Melon Slice")
                             .put(Material.MELON_STEM, "Melon Stem")
                             .put(Material.MILK_BUCKET, "Milk Bucket")
                             .put(Material.MINECART, "Minecart")
                             .put(Material.MOOSHROOM_SPAWN_EGG, "Mooshroom Spawn Egg")
                             .put(Material.MOSSY_COBBLESTONE, "Mossy Cobblestone")
                             .put(Material.MOSSY_COBBLESTONE_WALL, "Mossy Cobblestone Wall")
                             .put(Material.MOSSY_STONE_BRICKS, "Mossy Stone Bricks")
                             .put(Material.MOVING_PISTON, "Moving Piston")
                             .put(Material.MULE_SPAWN_EGG, "Mule Spawn Egg")
                             .put(Material.MUSHROOM_STEM, "Mushroom Stem")
                             .put(Material.MUSHROOM_STEW, "Mushroom Stew")
                             .put(Material.MUSIC_DISC_11, "Music Disc")
                             .put(Material.MUSIC_DISC_13, "Music Disc")
                             .put(Material.MUSIC_DISC_BLOCKS, "Music Disc")
                             .put(Material.MUSIC_DISC_CAT, "Music Disc")
                             .put(Material.MUSIC_DISC_CHIRP, "Music Disc")
                             .put(Material.MUSIC_DISC_FAR, "Music Disc")
                             .put(Material.MUSIC_DISC_MALL, "Music Disc")
                             .put(Material.MUSIC_DISC_MELLOHI, "Music Disc")
                             .put(Material.MUSIC_DISC_STAL, "Music Disc")
                             .put(Material.MUSIC_DISC_STRAD, "Music Disc")
                             .put(Material.MUSIC_DISC_WAIT, "Music Disc")
                             .put(Material.MUSIC_DISC_WARD, "Music Disc")
                             .put(Material.MUTTON, "Raw Mutton")
                             .put(Material.MYCELIUM, "Mycelium")
                             .put(Material.NAME_TAG, "Name Tag")
                             .put(Material.NAUTILUS_SHELL, "Nautilus Shell")
                             .put(Material.NETHERRACK, "Netherrack")
                             .put(Material.NETHER_BRICK, "Nether Brick")
                             .put(Material.NETHER_BRICKS, "Nether Bricks")
                             .put(Material.NETHER_BRICK_FENCE, "Nether Brick Fence")
                             .put(Material.NETHER_BRICK_SLAB, "Nether Brick Slab")
                             .put(Material.NETHER_BRICK_STAIRS, "Nether Brick Stairs")
                             .put(Material.NETHER_PORTAL, "Nether Portal")
                             .put(Material.NETHER_QUARTZ_ORE, "Nether Quartz Ore")
                             .put(Material.NETHER_STAR, "Nether Star")
                             .put(Material.NETHER_WART, "Nether Wart")
                             .put(Material.NETHER_WART_BLOCK, "Nether Wart Block")
                             .put(Material.NOTE_BLOCK, "Note Block")
                             .put(Material.OAK_BOAT, "Oak Boat")
                             .put(Material.OAK_BUTTON, "Oak Button")
                             .put(Material.OAK_DOOR, "Oak Door")
                             .put(Material.OAK_FENCE, "Oak Fence")
                             .put(Material.OAK_FENCE_GATE, "Oak Fence Gate")
                             .put(Material.OAK_LEAVES, "Oak Leaves")
                             .put(Material.OAK_LOG, "Oak Log")
                             .put(Material.OAK_PLANKS, "Oak Planks")
                             .put(Material.OAK_PRESSURE_PLATE, "Oak Pressure Plate")
                             .put(Material.OAK_SAPLING, "Oak Sapling")
                             .put(Material.OAK_SLAB, "Oak Slab")
                             .put(Material.OAK_STAIRS, "Oak Stairs")
                             .put(Material.OAK_TRAPDOOR, "Oak Trapdoor")
                             .put(Material.OAK_WOOD, "Oak Wood")
                             .put(Material.OBSERVER, "Observer")
                             .put(Material.OBSIDIAN, "Obsidian")
                             .put(Material.OCELOT_SPAWN_EGG, "Ocelot Spawn Egg")
                             .put(Material.ORANGE_BANNER, "Orange Banner")
                             .put(Material.ORANGE_BED, "Orange Bed")
                             .put(Material.ORANGE_CARPET, "Orange Carpet")
                             .put(Material.ORANGE_CONCRETE, "Orange Concrete")
                             .put(Material.ORANGE_CONCRETE_POWDER, "Orange Concrete Powder")
                             .put(Material.ORANGE_DYE, "Orange Dye")
                             .put(Material.ORANGE_GLAZED_TERRACOTTA, "Orange Glazed Terracotta")
                             .put(Material.ORANGE_SHULKER_BOX, "Orange Shulker Box")
                             .put(Material.ORANGE_STAINED_GLASS, "Orange Stained Glass")
                             .put(Material.ORANGE_STAINED_GLASS_PANE, "Orange Stained Glass Pane")
                             .put(Material.ORANGE_TERRACOTTA, "Orange Terracotta")
                             .put(Material.ORANGE_TULIP, "Orange Tulip")
                             .put(Material.ORANGE_WALL_BANNER, "Orange Banner")
                             .put(Material.ORANGE_WOOL, "Orange Wool")
                             .put(Material.OXEYE_DAISY, "Oxeye Daisy")
                             .put(Material.PACKED_ICE, "Packed Ice")
                             .put(Material.PAINTING, "Painting")
                             .put(Material.PAPER, "Paper")
                             .put(Material.PARROT_SPAWN_EGG, "Parrot Spawn Egg")
                             .put(Material.PEONY, "Peony")
                             .put(Material.PETRIFIED_OAK_SLAB, "Petrified Oak Slab")
                             .put(Material.PHANTOM_MEMBRANE, "Phantom Membrane")
                             .put(Material.PHANTOM_SPAWN_EGG, "Phantom Spawn Egg")
                             .put(Material.PIG_SPAWN_EGG, "Pig Spawn Egg")
                             .put(Material.PINK_BANNER, "Pink Banner")
                             .put(Material.PINK_BED, "Pink Bed")
                             .put(Material.PINK_CARPET, "Pink Carpet")
                             .put(Material.PINK_CONCRETE, "Pink Concrete")
                             .put(Material.PINK_CONCRETE_POWDER, "Pink Concrete Powder")
                             .put(Material.PINK_DYE, "Pink Dye")
                             .put(Material.PINK_GLAZED_TERRACOTTA, "Pink Glazed Terracotta")
                             .put(Material.PINK_SHULKER_BOX, "Pink Shulker Box")
                             .put(Material.PINK_STAINED_GLASS, "Pink Stained Glass")
                             .put(Material.PINK_STAINED_GLASS_PANE, "Pink Stained Glass Pane")
                             .put(Material.PINK_TERRACOTTA, "Pink Terracotta")
                             .put(Material.PINK_TULIP, "Pink Tulip")
                             .put(Material.PINK_WALL_BANNER, "Pink Banner")
                             .put(Material.PINK_WOOL, "Pink Wool")
                             .put(Material.PISTON, "Piston")
                             .put(Material.PISTON_HEAD, "Piston Head")
                             .put(Material.PLAYER_HEAD, "Player Head")
                             .put(Material.PLAYER_WALL_HEAD, "Player Wall Head")
                             .put(Material.PODZOL, "Podzol")
                             .put(Material.POISONOUS_POTATO, "Poisonous Potato")
                             .put(Material.POLAR_BEAR_SPAWN_EGG, "Polar Bear Spawn Egg")
                             .put(Material.POLISHED_ANDESITE, "Polished Andesite")
                             .put(Material.POLISHED_DIORITE, "Polished Diorite")
                             .put(Material.POLISHED_GRANITE, "Polished Granite")
                             .put(Material.POPPED_CHORUS_FRUIT, "Popped Chorus Fruit")
                             .put(Material.POPPY, "Poppy")
                             .put(Material.PORKCHOP, "Raw Porkchop")
                             .put(Material.POTATO, "Potato")
                             .put(Material.POTATOES, "Potatoes")
                             .put(Material.POTION, "Potion")
                             .put(Material.POTTED_ACACIA_SAPLING, "Potted Acacia Sapling")
                             .put(Material.POTTED_ALLIUM, "Potted Allium")
                             .put(Material.POTTED_AZURE_BLUET, "Potted Azure Bluet")
                             .put(Material.POTTED_BIRCH_SAPLING, "Potted Birch Sapling")
                             .put(Material.POTTED_BLUE_ORCHID, "Potted Blue Orchid")
                             .put(Material.POTTED_BROWN_MUSHROOM, "Potted Brown Mushroom")
                             .put(Material.POTTED_CACTUS, "Potted Cactus")
                             .put(Material.POTTED_DANDELION, "Potted Dandelion")
                             .put(Material.POTTED_DARK_OAK_SAPLING, "Potted Dark Oak Sapling")
                             .put(Material.POTTED_DEAD_BUSH, "Potted Dead Bush")
                             .put(Material.POTTED_FERN, "Potted Fern")
                             .put(Material.POTTED_JUNGLE_SAPLING, "Potted Jungle Sapling")
                             .put(Material.POTTED_OAK_SAPLING, "Potted Oak Sapling")
                             .put(Material.POTTED_ORANGE_TULIP, "Potted Orange Tulip")
                             .put(Material.POTTED_OXEYE_DAISY, "Potted Oxeye Daisy")
                             .put(Material.POTTED_PINK_TULIP, "Potted Pink Tulip")
                             .put(Material.POTTED_POPPY, "Potted Poppy")
                             .put(Material.POTTED_RED_MUSHROOM, "Potted Red Mushroom")
                             .put(Material.POTTED_RED_TULIP, "Potted Red Tulip")
                             .put(Material.POTTED_SPRUCE_SAPLING, "Potted Spruce Sapling")
                             .put(Material.POTTED_WHITE_TULIP, "Potted White Tulip")
                             .put(Material.POWERED_RAIL, "Powered Rail")
                             .put(Material.PRISMARINE, "Prismarine")
                             .put(Material.PRISMARINE_BRICKS, "Prismarine Bricks")
                             .put(Material.PRISMARINE_BRICK_SLAB, "Prismarine Brick Slab")
                             .put(Material.PRISMARINE_BRICK_STAIRS, "Prismarine Brick Stairs")
                             .put(Material.PRISMARINE_CRYSTALS, "Prismarine Crystals")
                             .put(Material.PRISMARINE_SHARD, "Prismarine Shard")
                             .put(Material.PRISMARINE_SLAB, "Prismarine Slab")
                             .put(Material.PRISMARINE_STAIRS, "Prismarine Stairs")
                             .put(Material.PUFFERFISH, "Pufferfish")
                             .put(Material.PUFFERFISH_BUCKET, "Bucket of Pufferfish")
                             .put(Material.PUFFERFISH_SPAWN_EGG, "Pufferfish Spawn Egg")
                             .put(Material.PUMPKIN, "Pumpkin")
                             .put(Material.PUMPKIN_PIE, "Pumpkin Pie")
                             .put(Material.PUMPKIN_SEEDS, "Pumpkin Seeds")
                             .put(Material.PUMPKIN_STEM, "Pumpkin Stem")
                             .put(Material.PURPLE_BANNER, "Purple Banner")
                             .put(Material.PURPLE_BED, "Purple Bed")
                             .put(Material.PURPLE_CARPET, "Purple Carpet")
                             .put(Material.PURPLE_CONCRETE, "Purple Concrete")
                             .put(Material.PURPLE_CONCRETE_POWDER, "Purple Concrete Powder")
                             .put(Material.PURPLE_DYE, "Purple Dye")
                             .put(Material.PURPLE_GLAZED_TERRACOTTA, "Purple Glazed Terracotta")
                             .put(Material.PURPLE_SHULKER_BOX, "Purple Shulker Box")
                             .put(Material.PURPLE_STAINED_GLASS, "Purple Stained Glass")
                             .put(Material.PURPLE_STAINED_GLASS_PANE, "Purple Stained Glass Pane")
                             .put(Material.PURPLE_TERRACOTTA, "Purple Terracotta")
                             .put(Material.PURPLE_WALL_BANNER, "Purple Banner")
                             .put(Material.PURPLE_WOOL, "Purple Wool")
                             .put(Material.PURPUR_BLOCK, "Purpur Block")
                             .put(Material.PURPUR_PILLAR, "Purpur Pillar")
                             .put(Material.PURPUR_SLAB, "Purpur Slab")
                             .put(Material.PURPUR_STAIRS, "Purpur Stairs")
                             .put(Material.QUARTZ, "Nether Quartz")
                             .put(Material.QUARTZ_BLOCK, "Block of Quartz")
                             .put(Material.QUARTZ_PILLAR, "Quartz Pillar")
                             .put(Material.QUARTZ_SLAB, "Quartz Slab")
                             .put(Material.QUARTZ_STAIRS, "Quartz Stairs")
                             .put(Material.RABBIT, "Raw Rabbit")
                             .put(Material.RABBIT_FOOT, "Rabbit's Foot")
                             .put(Material.RABBIT_HIDE, "Rabbit Hide")
                             .put(Material.RABBIT_SPAWN_EGG, "Rabbit Spawn Egg")
                             .put(Material.RABBIT_STEW, "Rabbit Stew")
                             .put(Material.RAIL, "Rail")
                             .put(Material.REDSTONE, "Redstone")
                             .put(Material.REDSTONE_BLOCK, "Block of Redstone")
                             .put(Material.REDSTONE_LAMP, "Redstone Lamp")
                             .put(Material.REDSTONE_ORE, "Redstone Ore")
                             .put(Material.REDSTONE_TORCH, "Redstone Torch")
                             .put(Material.REDSTONE_WALL_TORCH, "Redstone Wall Torch")
                             .put(Material.REDSTONE_WIRE, "Redstone Dust")
                             .put(Material.RED_BANNER, "Red Banner")
                             .put(Material.RED_BED, "Red Bed")
                             .put(Material.RED_CARPET, "Red Carpet")
                             .put(Material.RED_CONCRETE, "Red Concrete")
                             .put(Material.RED_CONCRETE_POWDER, "Red Concrete Powder")
                             .put(Material.RED_GLAZED_TERRACOTTA, "Red Glazed Terracotta")
                             .put(Material.RED_MUSHROOM, "Red Mushroom")
                             .put(Material.RED_MUSHROOM_BLOCK, "Red Mushroom Block")
                             .put(Material.RED_NETHER_BRICKS, "Red Nether Bricks")
                             .put(Material.RED_SAND, "Red Sand")
                             .put(Material.RED_SANDSTONE, "Red Sandstone")
                             .put(Material.RED_SANDSTONE_SLAB, "Red Sandstone Slab")
                             .put(Material.RED_SANDSTONE_STAIRS, "Red Sandstone Stairs")
                             .put(Material.RED_SHULKER_BOX, "Red Shulker Box")
                             .put(Material.RED_STAINED_GLASS, "Red Stained Glass")
                             .put(Material.RED_STAINED_GLASS_PANE, "Red Stained Glass Pane")
                             .put(Material.RED_TERRACOTTA, "Red Terracotta")
                             .put(Material.RED_TULIP, "Red Tulip")
                             .put(Material.RED_WALL_BANNER, "Red Banner")
                             .put(Material.RED_WOOL, "Red Wool")
                             .put(Material.REPEATER, "Redstone Repeater")
                             .put(Material.REPEATING_COMMAND_BLOCK, "Repeating Command Block")
                             .put(Material.ROSE_BUSH, "Rose Bush")
                             .put(Material.ROSE_RED, "Rose Red")
                             .put(Material.ROTTEN_FLESH, "Rotten Flesh")
                             .put(Material.SADDLE, "Saddle")
                             .put(Material.SALMON, "Raw Salmon")
                             .put(Material.SALMON_BUCKET, "Bucket of Salmon")
                             .put(Material.SALMON_SPAWN_EGG, "Salmon Spawn Egg")
                             .put(Material.SAND, "Sand")
                             .put(Material.SANDSTONE, "Sandstone")
                             .put(Material.SANDSTONE_SLAB, "Sandstone Slab")
                             .put(Material.SANDSTONE_STAIRS, "Sandstone Stairs")
                             .put(Material.SCUTE, "Scute")
                             .put(Material.SEAGRASS, "Seagrass")
                             .put(Material.SEA_LANTERN, "Sea Lantern")
                             .put(Material.SEA_PICKLE, "Sea Pickle")
                             .put(Material.SHEARS, "Shears")
                             .put(Material.SHEEP_SPAWN_EGG, "Sheep Spawn Egg")
                             .put(Material.SHIELD, "Shield")
                             .put(Material.SHULKER_BOX, "Shulker Box")
                             .put(Material.SHULKER_SHELL, "Shulker Shell")
                             .put(Material.SHULKER_SPAWN_EGG, "Shulker Spawn Egg")
                             .put(Material.SIGN, "Sign")
                             .put(Material.SILVERFISH_SPAWN_EGG, "Silverfish Spawn Egg")
                             .put(Material.SKELETON_HORSE_SPAWN_EGG, "Skeleton Horse Spawn Egg")
                             .put(Material.SKELETON_SKULL, "Skeleton Skull")
                             .put(Material.SKELETON_SPAWN_EGG, "Skeleton Spawn Egg")
                             .put(Material.SKELETON_WALL_SKULL, "Skeleton Wall Skull")
                             .put(Material.SLIME_BALL, "Slimeball")
                             .put(Material.SLIME_BLOCK, "Slime Block")
                             .put(Material.SLIME_SPAWN_EGG, "Slime Spawn Egg")
                             .put(Material.SMOOTH_QUARTZ, "Smooth Quartz")
                             .put(Material.SMOOTH_RED_SANDSTONE, "Smooth Red Sandstone")
                             .put(Material.SMOOTH_SANDSTONE, "Smooth Sandstone")
                             .put(Material.SMOOTH_STONE, "Smooth Stone")
                             .put(Material.SNOW, "Snow")
                             .put(Material.SNOWBALL, "Snowball")
                             .put(Material.SNOW_BLOCK, "Snow Block")
                             .put(Material.SOUL_SAND, "Soul Sand")
                             .put(Material.SPAWNER, "Spawner")
                             .put(Material.SPECTRAL_ARROW, "Spectral Arrow")
                             .put(Material.SPIDER_EYE, "Spider Eye")
                             .put(Material.SPIDER_SPAWN_EGG, "Spider Spawn Egg")
                             .put(Material.SPLASH_POTION, "Splash Potion")
                             .put(Material.SPONGE, "Sponge")
                             .put(Material.SPRUCE_BOAT, "Spruce Boat")
                             .put(Material.SPRUCE_BUTTON, "Spruce Button")
                             .put(Material.SPRUCE_DOOR, "Spruce Door")
                             .put(Material.SPRUCE_FENCE, "Spruce Fence")
                             .put(Material.SPRUCE_FENCE_GATE, "Spruce Fence Gate")
                             .put(Material.SPRUCE_LEAVES, "Spruce Leaves")
                             .put(Material.SPRUCE_LOG, "Spruce Log")
                             .put(Material.SPRUCE_PLANKS, "Spruce Planks")
                             .put(Material.SPRUCE_PRESSURE_PLATE, "Spruce Pressure Plate")
                             .put(Material.SPRUCE_SAPLING, "Spruce Sapling")
                             .put(Material.SPRUCE_SLAB, "Spruce Slab")
                             .put(Material.SPRUCE_STAIRS, "Spruce Stairs")
                             .put(Material.SPRUCE_TRAPDOOR, "Spruce Trapdoor")
                             .put(Material.SPRUCE_WOOD, "Spruce Wood")
                             .put(Material.SQUID_SPAWN_EGG, "Squid Spawn Egg")
                             .put(Material.STICK, "Stick")
                             .put(Material.STICKY_PISTON, "Sticky Piston")
                             .put(Material.STONE, "Stone")
                             .put(Material.STONE_AXE, "Stone Axe")
                             .put(Material.STONE_BRICKS, "Stone Bricks")
                             .put(Material.STONE_BRICK_SLAB, "Stone Brick Slab")
                             .put(Material.STONE_BRICK_STAIRS, "Stone Brick Stairs")
                             .put(Material.STONE_BUTTON, "Stone Button")
                             .put(Material.STONE_HOE, "Stone Hoe")
                             .put(Material.STONE_PICKAXE, "Stone Pickaxe")
                             .put(Material.STONE_PRESSURE_PLATE, "Stone Pressure Plate")
                             .put(Material.STONE_SHOVEL, "Stone Shovel")
                             .put(Material.STONE_SLAB, "Stone Slab")
                             .put(Material.STONE_SWORD, "Stone Sword")
                             .put(Material.STRAY_SPAWN_EGG, "Stray Spawn Egg")
                             .put(Material.STRING, "String")
                             .put(Material.STRIPPED_ACACIA_LOG, "Stripped Acacia Log")
                             .put(Material.STRIPPED_ACACIA_WOOD, "Stripped Acacia Wood")
                             .put(Material.STRIPPED_BIRCH_LOG, "Stripped Birch Log")
                             .put(Material.STRIPPED_BIRCH_WOOD, "Stripped Birch Wood")
                             .put(Material.STRIPPED_DARK_OAK_LOG, "Stripped Dark Oak Log")
                             .put(Material.STRIPPED_DARK_OAK_WOOD, "Stripped Dark Oak Wood")
                             .put(Material.STRIPPED_JUNGLE_LOG, "Stripped Jungle Log")
                             .put(Material.STRIPPED_JUNGLE_WOOD, "Stripped Jungle Wood")
                             .put(Material.STRIPPED_OAK_LOG, "Stripped Oak Log")
                             .put(Material.STRIPPED_OAK_WOOD, "Stripped Oak Wood")
                             .put(Material.STRIPPED_SPRUCE_LOG, "Stripped Spruce Log")
                             .put(Material.STRIPPED_SPRUCE_WOOD, "Stripped Spruce Wood")
                             .put(Material.STRUCTURE_BLOCK, "Structure Block")
                             .put(Material.STRUCTURE_VOID, "Structure Void")
                             .put(Material.SUGAR, "Sugar")
                             .put(Material.SUGAR_CANE, "Sugar Cane")
                             .put(Material.SUNFLOWER, "Sunflower")
                             .put(Material.TALL_GRASS, "Tall Grass")
                             .put(Material.TALL_SEAGRASS, "Tall Seagrass")
                             .put(Material.TERRACOTTA, "Terracotta")
                             .put(Material.TIPPED_ARROW, "Tipped Arrow")
                             .put(Material.TNT, "TNT")
                             .put(Material.TNT_MINECART, "Minecart with TNT")
                             .put(Material.TORCH, "Torch")
                             .put(Material.TOTEM_OF_UNDYING, "Totem of Undying")
                             .put(Material.TRAPPED_CHEST, "Trapped Chest")
                             .put(Material.TRIDENT, "Trident")
                             .put(Material.TRIPWIRE, "Tripwire")
                             .put(Material.TRIPWIRE_HOOK, "Tripwire Hook")
                             .put(Material.TROPICAL_FISH, "Tropical Fish")
                             .put(Material.TROPICAL_FISH_BUCKET, "Bucket of Tropical Fish")
                             .put(Material.TROPICAL_FISH_SPAWN_EGG, "Tropical Fish Spawn Egg")
                             .put(Material.TUBE_CORAL, "Tube Coral")
                             .put(Material.TUBE_CORAL_BLOCK, "Tube Coral Block")
                             .put(Material.TUBE_CORAL_FAN, "Tube Coral Fan")
                             .put(Material.TUBE_CORAL_WALL_FAN, "Tube Coral Wall Fan")
                             .put(Material.TURTLE_EGG, "Turtle Egg")
                             .put(Material.TURTLE_HELMET, "Turtle Shell")
                             .put(Material.TURTLE_SPAWN_EGG, "Turtle Spawn Egg")
                             .put(Material.VEX_SPAWN_EGG, "Vex Spawn Egg")
                             .put(Material.VILLAGER_SPAWN_EGG, "Villager Spawn Egg")
                             .put(Material.VINDICATOR_SPAWN_EGG, "Vindicator Spawn Egg")
                             .put(Material.VINE, "Vines")
                             .put(Material.VOID_AIR, "Void Air")
                             .put(Material.WALL_SIGN, "Wall Sign")
                             .put(Material.WALL_TORCH, "Wall Torch")
                             .put(Material.WATER, "Water")
                             .put(Material.WATER_BUCKET, "Water Bucket")
                             .put(Material.WET_SPONGE, "Wet Sponge")
                             .put(Material.WHEAT, "Wheat Crops")
                             .put(Material.WHEAT_SEEDS, "Wheat Seeds")
                             .put(Material.WHITE_BANNER, "White Banner")
                             .put(Material.WHITE_BED, "White Bed")
                             .put(Material.WHITE_CARPET, "White Carpet")
                             .put(Material.WHITE_CONCRETE, "White Concrete")
                             .put(Material.WHITE_CONCRETE_POWDER, "White Concrete Powder")
                             .put(Material.WHITE_GLAZED_TERRACOTTA, "White Glazed Terracotta")
                             .put(Material.WHITE_SHULKER_BOX, "White Shulker Box")
                             .put(Material.WHITE_STAINED_GLASS, "White Stained Glass")
                             .put(Material.WHITE_STAINED_GLASS_PANE, "White Stained Glass Pane")
                             .put(Material.WHITE_TERRACOTTA, "White Terracotta")
                             .put(Material.WHITE_TULIP, "White Tulip")
                             .put(Material.WHITE_WALL_BANNER, "White Banner")
                             .put(Material.WHITE_WOOL, "White Wool")
                             .put(Material.WITCH_SPAWN_EGG, "Witch Spawn Egg")
                             .put(Material.WITHER_SKELETON_SKULL, "Wither Skeleton Skull")
                             .put(Material.WITHER_SKELETON_SPAWN_EGG, "Wither Skeleton Spawn Egg")
                             .put(Material.WITHER_SKELETON_WALL_SKULL, "Wither Skeleton Wall Skull")
                             .put(Material.WOLF_SPAWN_EGG, "Wolf Spawn Egg")
                             .put(Material.WOODEN_AXE, "Wooden Axe")
                             .put(Material.WOODEN_HOE, "Wooden Hoe")
                             .put(Material.WOODEN_PICKAXE, "Wooden Pickaxe")
                             .put(Material.WOODEN_SHOVEL, "Wooden Shovel")
                             .put(Material.WOODEN_SWORD, "Wooden Sword")
                             .put(Material.WRITABLE_BOOK, "Book and Quill")
                             .put(Material.WRITTEN_BOOK, "Written Book")
                             .put(Material.YELLOW_BANNER, "Yellow Banner")
                             .put(Material.YELLOW_BED, "Yellow Bed")
                             .put(Material.YELLOW_CARPET, "Yellow Carpet")
                             .put(Material.YELLOW_CONCRETE, "Yellow Concrete")
                             .put(Material.YELLOW_CONCRETE_POWDER, "Yellow Concrete Powder")
                             .put(Material.YELLOW_GLAZED_TERRACOTTA, "Yellow Glazed Terracotta")
                             .put(Material.YELLOW_SHULKER_BOX, "Yellow Shulker Box")
                             .put(Material.YELLOW_STAINED_GLASS, "Yellow Stained Glass")
                             .put(Material.YELLOW_STAINED_GLASS_PANE, "Yellow Stained Glass Pane")
                             .put(Material.YELLOW_TERRACOTTA, "Yellow Terracotta")
                             .put(Material.YELLOW_WALL_BANNER, "Yellow Banner")
                             .put(Material.YELLOW_WOOL, "Yellow Wool")
                             .put(Material.ZOMBIE_HEAD, "Zombie Head")
                             .put(Material.ZOMBIE_HORSE_SPAWN_EGG, "Zombie Horse Spawn Egg")
                             .put(Material.ZOMBIE_PIGMAN_SPAWN_EGG, "Zombie Pigman Spawn Egg")
                             .put(Material.ZOMBIE_SPAWN_EGG, "Zombie Spawn Egg")
                             .put(Material.ZOMBIE_VILLAGER_SPAWN_EGG, "Zombie Villager Spawn Egg")
                             .put(Material.ZOMBIE_WALL_HEAD, "Zombie Wall Head").build();
    }

    /**
     * Given an item stack, return a friendly printable name for the item, as
     * the (English-language) vanilla Minecraft client would display it.
     *
     * @param stack the item stack
     *
     * @return a friendly printable name for the item
     */
    public static String lookup(ItemStack stack)
    {
        if (stack == null || stack.getType() == Material.AIR)
        {
            return "Fist";
        }
        if (stack.hasItemMeta())
        {
            ItemMeta meta = stack.getItemMeta();
            if (meta.getDisplayName() != null)
            {
                return meta.getDisplayName();
            }
            else if (meta instanceof BookMeta)
            {
                return ((BookMeta) meta).getTitle();
            }
        }
        return ITEM_NAMES.containsKey(stack.getType()) ? ITEM_NAMES.get(stack.getType()) : stack.getType().toString();
    }

    public static String lookup(MaterialData data)
    {
        return lookup(data.toItemStack(1));
    }

    public static String lookup(Material material)
    {
        return lookup(new ItemStack(material));
    }

    /**
     * Given a block, return a friendly printable name for the block, as the
     * (English-language) vanilla Minecraft client would display it.
     *
     * @param block the block
     *
     * @return a friendly printable name for the block
     */
    public static String lookup(Block block)
    {
        return lookup(new ItemStack(block.getType(), 1, block.getData()));
    }

    /**
     * Given an item stack return a friendly name for the item, in the form
     * "{amount} x {item-name}" where {amount} is the number of items in the
     * stack and {item-name} is the return value of
     * {@link #lookup(org.bukkit.inventory.ItemStack)} .
     *
     * @param stack the item stack
     *
     * @return a friendly printable name for the item, with amount information
     */
    public static String lookupWithAmount(ItemStack stack)
    {
        return stack.getAmount() + " x " + lookup(stack);
    }

}
